services:
  api:
    build: .
    image: val/api:dev
    ports: ["3000:3000"]
    environment:
      - PORT=3000
      - NODE_ENV=development
    depends_on: [db, redis]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  dbdata: {}