apiVersion: apps/v1
kind: Deployment
metadata:
  name: val-api
spec:
  replicas: 2
  selector:
    matchLabels: { app: val-api }
  template:
    metadata:
      labels: { app: val-api }
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/val-api:latest
          ports: [{ containerPort: 3000 }]
          env:
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }