name: CI

on:
  push:
    branches: [main, feature/test-ci]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { node: [18, 20] }

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            app/package-lock.json

      - name: Install deps
        run: npm ci
        working-directory: app                          

      - name: Lint
        run: npm run lint --if-present
        working-directory: app

      - name: Test
        run: npm test --if-present
        working-directory: app

      - name: Build
        run: npm run build --if-present
        working-directory: app

  docker-image:
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .         # Dockerfile в корне
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/val-api:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/val-api:latest